### ISSUE TITLE
Terraform Error: Failed to query available provider packages

### ISSUE THREAD

**Issue by chris2k20** [slauger/hcloud-okd4#135] opened 2021-03-16 18:58 UTC
First thanks for your work on this project ! :)

When running `make infrastructure BOOTSTRAP=true` I get the following error [okd.log](https://github.com/slauger/hcloud-okd4/files/6151582/okd.log)
: 

```
...
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/hcloud: provider registry registry.terraform.io does not have a
provider named registry.terraform.io/hashicorp/hcloud


Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/cloudflare: provider registry registry.terraform.io does not have a
provider named registry.terraform.io/hashicorp/cloudflare

make: *** [Makefile:86: infrastructure] Error 1
```

I already performed some actions on the terraform versions.tf but without success..

**Comment by slauger** [comment] 2021-03-16 19:13
Hi @chris2k20,

this is caused by the new terraform version and should be fixed in the feature branch upgrade-to-4.7.x. Well, enable Renovate with auto merge wasn't the best idea... :)

https://github.com/slauger/hcloud-okd4/tree/feat/upgrade-to-4.7.x

There are currently three major problems that I am currently working on in this branch:

- Something changed in the cluster bootstrap with OKD 4.7. I did not had luck installing OKD 4.7 on hcloud yet. Your help is appreciated.  :(
- The default resolvers from hcloud have a very strange caching mechanism and ignore the TTL from Cloudflare. A newly created record (e. g. `api-int.cluster-id.basedomain.tld`) is resolvable after about 60 minutes. This record is required for the inital boot of all master/worker nodes -> we need somehow override the dns servers provided by dhcp and switch to custom dns servers / cloudflare (during the first boot!)
- RPC Bind is reachable from the public internet by default (this could be fixed with the new firewall beta feature which is available since today -> https://www.hetzner.com/news/03-21-firewall-beta/)

The poor I/O performance of the hcloud (which could cause etcd issues) still remains unsolved.

**Comment by slauger** [comment] 2021-03-16 19:13
@jomeier FYI

**Comment by nustiueudinastea** [comment] 2021-05-14 17:19
Should this be closed?

**Comment by slauger** [comment] 2021-05-24 08:57
The problems still persist. I think we're leaving the issue open.

**Closed** 2021-06-29 21:15 UTC
